services:
  oncater_backend:
    image: ghcr.io/intuition-business/timshel/backend:production
    mem_limit: 1G
    mem_reservation: 512M
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000